name: Idea for a new feature
description: Using this form, you can suggest to us your idea for implementation in the bot.
title: New idea
labels: 
  - enhancement

body: 
  - type: checkboxes
    attributes:
      label: "Preliminary checks"
      description: "Check here the items that relate to your idea."
      options:
        - label: "I'm sure I'm not blocked in the bot"
          required: true
        - label: "I'm sure this idea hasn't been proposed before"
          required: true
        - label: "This idea involves use in certain regions."
        - label: "My idea has not previously been implemented or is not planned for release in the update."
          required: true
        - label: "I am familiar with the rules for submitting ideas."
          required: true
        - label: "I plan to offer updates/additions to this idea periodically."
        - label: "My idea requires interaction with other services."

  - type: markdown
    attributes:
      value: "## Tell us more about your idea."
  - type: markdown
    attributes:
      value: |
        We need you to answer a few questions here about your idea so that we can understand what you want to add.
        *Follow the news and updates in our Telegram channel.*
    
  - type: dropdown
    attributes:
      label: "On which platforms do you want to add your idea?"
      multiple: true
      options:
        - Telegram
        - Discord
        - Twitch
        - VK
    validations:
      required: true

  - type: input
    attributes:
      label: "Your Telegram ID / VIA ID"
      description: "Share your Telegram ID or VIA_ID so we can contact you if we would like to discuss the idea in more detail."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "If you have an example of implementing this idea in Python or Cython, write here."
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        from ... import ...

        async def main():
          # Something
      render: python
  - type: markdown
    attributes:
      value: |
        If the code of your idea is written in another programming language, then it’s okay, we support any other programming language listed below!
        But the main thing is that your code can accept data in JSON format; if this is not the case, then unfortunately the example of your idea is not suitable. 
        Kotlin
        C++
        JS / TS

  - type: textarea
    attributes:
      label: "What will your idea contribute?"
      description: "Please share information about what new features your idea will bring and why it is needed."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Tell us about your idea."
      description: "Describe how your idea should work and what it should bring as a result."
    validations:
      required: true
